language: python
python:
  - "2.7"
sudo: required
before_install:
  - "wget https://snap.stanford.edu/snappy/release/snap-1.2-2.4-centos6.5-x64-py2.6.tar.gz"
  - "tar zxf snap-1.2-2.4-centos6.5-x64-py2.6.tar.gz"
  - "cd snap-1.2-2.4-centos6.5-x64-py2.6/"
  - "python setup.py install --user"
# command to install dependencies
install: "python2.7 setup.py install --user"
# command to run tests
script: nosetests
